name: bidcart
description: "BidCart"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  email_validator: '^2.1.16'
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  # add this line to your dependencies
  fluttertoast: ^8.2.4
  motion_toast: ^2.7.10
  cloud_firestore: ^4.15.4
  get: ^4.6.1
  get_storage: ^2.0.3
  flutter_native_splash: ^2.3.10
  google_sign_in: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.0.0
  carousel_slider: ^4.2.1
  firebase_storage: ^11.6.10
  cached_network_image: ^3.3.1
  easy_search_bar: ^2.5.0
  intl: ^0.19.0
  firebase_app_check: ^0.2.2+1
  connectivity_plus: ^6.0.2
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_map_math: ^0.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter_native_splash:
  color: "#FFFFFF"

  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png

  web: false



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/explore_products_images/
    - assets/logo/
    - assets/products_images/
    - assets/animations/

    #- assets/products/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Preahvihear
      fonts:
       - asset: assets/fonts/Preahvihear-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
